/**
 * llama-server parameter table (PLAN §10.1, verified against `--help`
 * of the user's build 67672dc5 — task 2.4).
 *
 * Flag notes (build 67672dc5):
 * - `--n-gpu-layers` accepts an exact number | `auto` | `all`;
 * - `--flash-attn` = on | off | auto (default auto);
 * - `--fit` = on | off (default on); `--slots`/`--ui` are on by default
 *   and disabled via `--no-slots` / `--no-ui`;
 * - `--offline` and `--metrics` are flag-only (present = enabled).
 *
 * Bool convention in args.ts:
 * - plain bool (default true, no off*): flag sent when true (`--metrics`, `--offline`);
 * - bool + offFlag: `offFlag` sent when false (`--no-slots`, `--no-ui`);
 * - bool + offValue: `flag + offValue` sent when false (`--fit off`).
 */
import type { ParamSchema } from '../types.js';

export const LLAMA_SERVER_SCHEMA: ParamSchema[] = [
  // --- model
  {
    key: 'model',
    label: 'Model (plik GGUF)',
    type: 'path-model',
    flag: '--model',
    default: undefined,
    group: 'model',
  },
  {
    key: 'context-size',
    label: 'Rozmiar kontekstu',
    type: 'int',
    flag: '--ctx-size',
    default: 0,
    min: 0,
    group: 'model',
    description: '0 = z modelu',
  },
  {
    key: 'cache-type-k',
    label: 'Typ cache K',
    type: 'enum',
    flag: '--cache-type-k',
    default: 'q4_1',
    choices: [
      { value: 'f16' },
      { value: 'f32' },
      { value: 'bf16' },
      { value: 'q8_0' },
      { value: 'q5_0' },
      { value: 'q5_1' },
      { value: 'q4_0' },
      { value: 'q4_1' },
    ],
    group: 'model',
    advanced: true,
  },
  {
    key: 'cache-type-v',
    label: 'Typ cache V',
    type: 'enum',
    flag: '--cache-type-v',
    default: 'q4_1',
    choices: [
      { value: 'f16' },
      { value: 'f32' },
      { value: 'bf16' },
      { value: 'q8_0' },
      { value: 'q5_0' },
      { value: 'q5_1' },
      { value: 'q4_0' },
      { value: 'q4_1' },
    ],
    group: 'model',
    advanced: true,
  },
  // --- performance
  {
    key: 'gpu-layers',
    label: 'Warstwy na GPU',
    type: 'enum',
    flag: '--n-gpu-layers',
    default: 'auto',
    allowNumber: true,
    choices: [
      { value: 'auto' },
      { value: 'all' },
    ],
    group: 'performance',
    description: 'liczba, auto lub all',
  },
  {
    key: 'threads',
    label: 'Wątki CPU',
    type: 'int',
    flag: '--threads',
    default: -1,
    min: -1,
    group: 'performance',
    description: '-1 = liczba rdzeni CPU',
  },
  {
    key: 'batch-size',
    label: 'Rozmiar partii (batch)',
    type: 'int',
    flag: '--batch-size',
    default: 2048,
    min: 0,
    group: 'performance',
    advanced: true,
  },
  {
    key: 'ubatch-size',
    label: 'Fizyczny rozmiar partii (ubatch)',
    type: 'int',
    flag: '--ubatch-size',
    default: 1024,
    min: 0,
    group: 'performance',
    advanced: true,
  },
  {
    key: 'load-mode',
    label: 'Tryb ładowania',
    type: 'enum',
    flag: '--load-mode',
    default: 'auto',
    choices: [
      { value: 'auto' },
      { value: 'mmap' },
      { value: 'mlock' },
      { value: 'dio' },
    ],
    group: 'performance',
    advanced: true,
  },
  {
    key: 'flash-attn',
    label: 'Flash Attention',
    type: 'enum',
    flag: '--flash-attn',
    default: 'auto',
    choices: [
      { value: 'on' },
      { value: 'off' },
      { value: 'auto' },
    ],
    group: 'performance',
    advanced: true,
  },
  {
    key: 'device',
    label: 'Urządzenia GPU',
    type: 'string',
    flag: '--device',
    default: '',
    group: 'performance',
    advanced: true,
    description: 'np. dev1,dev2',
  },
  {
    key: 'fit',
    label: 'Automatyczne dopasowanie do VRAM (fit)',
    type: 'bool',
    flag: '--fit',
    offValue: 'off',
    default: true,
    group: 'performance',
    advanced: true,
  },
  // --- sampling
  {
    key: 'seed',
    label: 'Ziarno RNG (seed)',
    type: 'int',
    flag: '--seed',
    default: -1,
    group: 'sampling',
    advanced: true,
    description: '-1 = losowe',
  },
  {
    key: 'temp',
    label: 'Temperatura',
    type: 'float',
    flag: '--temp',
    default: 0.8,
    min: 0,
    group: 'sampling',
  },
  {
    key: 'top-p',
    label: 'Top-p',
    type: 'float',
    flag: '--top-p',
    default: 0.95,
    min: 0,
    max: 1,
    group: 'sampling',
  },
  {
    key: 'top-k',
    label: 'Top-k',
    type: 'int',
    flag: '--top-k',
    default: 40,
    min: 0,
    group: 'sampling',
  },
  {
    key: 'min-p',
    label: 'Min-p',
    type: 'float',
    flag: '--min-p',
    default: 0.05,
    min: 0,
    max: 1,
    group: 'sampling',
    advanced: true,
  },
  {
    key: 'typical-p',
    label: 'Typical-p',
    type: 'float',
    flag: '--typical-p',
    default: 1.0,
    min: 0,
    max: 1,
    group: 'sampling',
    advanced: true,
  },
  {
    key: 'max-tokens',
    label: 'Maksymalna liczba tokenów',
    type: 'int',
    flag: '--n-predict',
    default: -1,
    min: -1,
    group: 'sampling',
    description: '-1 = bez limitu',
  },
  // --- speculative
  {
    key: 'spec-model',
    label: 'Model spekulatywny (draft)',
    type: 'path-model',
    flag: '--spec-draft-model',
    default: null,
    group: 'speculative',
    advanced: true,
  },
  {
    key: 'n-draft',
    label: 'Maksymalna liczba tokenów draftowych (n-max)',
    type: 'int',
    flag: '--spec-draft-n-max',
    default: 3,
    min: 0,
    group: 'speculative',
    advanced: true,
  },
  {
    key: 'spec-type',
    label: 'Typ dekodowania spekulatywnego',
    type: 'enum',
    flag: '--spec-type',
    default: 'none',
    choices: [
      { value: 'none' },
      { value: 'draft-simple' },
      { value: 'draft-eagle3' },
      { value: 'draft-mtp' },
      { value: 'draft-dflash' },
      { value: 'draft-dspark' },
      { value: 'ngram-simple' },
      { value: 'ngram-map-k' },
      { value: 'ngram-map-k4v' },
      { value: 'ngram-mod' },
      { value: 'ngram-cache' },
    ],
    group: 'speculative',
    advanced: true,
  },
  {
    key: 'spec-type-k',
    label: 'Typ cache K (spekulacja)',
    type: 'enum',
    flag: '--spec-draft-type-k',
    default: 'f16',
    choices: [
      { value: 'f16' },
      { value: 'f32' },
      { value: 'q8_0' },
      { value: 'q4_1' },
    ],
    group: 'speculative',
    advanced: true,
  },
  {
    key: 'spec-type-v',
    label: 'Typ cache V (spekulacja)',
    type: 'enum',
    flag: '--spec-draft-type-v',
    default: 'f16',
    choices: [
      { value: 'f16' },
      { value: 'f32' },
      { value: 'q8_0' },
      { value: 'q4_1' },
    ],
    group: 'speculative',
    advanced: true,
  },
  // --- server
  {
    key: 'parallel',
    label: 'Sloty równoległe (parallel)',
    type: 'int',
    flag: '--parallel',
    default: -1,
    min: -1,
    group: 'server',
    advanced: true,
    description: '-1 = auto',
  },
  {
    key: 'api-key',
    label: 'Klucz API',
    type: 'string',
    flag: '--api-key',
    default: '',
    group: 'server',
    advanced: true,
  },
  {
    key: 'metrics-enabled',
    label: 'Endpoint metryk (Prometheus)',
    type: 'bool',
    flag: '--metrics',
    default: true,
    group: 'server',
    advanced: true,
  },
  {
    key: 'slots-endpoint',
    label: 'Endpoint slotów',
    type: 'bool',
    flag: '--slots',
    offFlag: '--no-slots',
    default: true,
    group: 'server',
    advanced: true,
  },
  {
    key: 'web-ui',
    label: 'Własny Web UI backendu',
    type: 'bool',
    flag: '--ui',
    offFlag: '--no-ui',
    default: true,
    group: 'server',
    advanced: true,
  },
  {
    key: 'host',
    label: 'Adres nasłuchu',
    type: 'string',
    flag: '--host',
    default: '127.0.0.1',
    group: 'server',
  },
  {
    key: 'port',
    label: 'Port',
    type: 'int',
    flag: '--port',
    default: 8080,
    min: 1024,
    max: 65535,
    group: 'server',
  },
  // --- vision (mmproj)
  {
    key: 'mmproj',
    label: 'Ścieżka do mmproj (vision)',
    type: 'path-model',
    flag: '--mmproj',
    default: null,
    group: 'vision',
    advanced: true,
    description: 'Plik GGUF mmproj — uruchamia obsługę obrazów',
  },
  {
    key: 'no-mmproj-offload',
    label: 'mmproj na CPU (bez offload na GPU)',
    type: 'bool',
    flag: '--no-mmproj-offload',
    default: false,
    group: 'vision',
    advanced: true,
    description: 'Włącza = mmproj w RAM, wyłącza = mmproj w VRAM',
  },
  // --- MoE
  {
    key: 'n-cpu-moe',
    label: 'Liczba warstw MoE na CPU',
    type: 'int',
    flag: '--n-cpu-moe',
    default: -1,
    min: -1,
    group: 'moe',
    advanced: true,
    description: '-1 = auto (wszystkie na CPU, gdy MoE)',
  },
  {
    key: 'no-mmap',
    label: 'Wyłącz mmap (--no-mmap)',
    type: 'bool',
    flag: '--no-mmap',
    default: false,
    group: 'moe',
    advanced: true,
    description: 'Potrzebne dla modeli MoE (cały model w RAM)',
  },
  // --- advanced
  {
    key: 'reasoning-effort',
    label: 'Wysiłek rozumowania (reasoning effort)',
    type: 'enum',
    flag: '--reasoning-effort',
    default: '',
    choices: [
      { value: 'low' },
      { value: 'medium' },
      { value: 'xhigh' },
    ],
    group: 'advanced',
    advanced: true,
  },
  {
    key: 'reasoning-format',
    label: 'Format rozumowania (reasoning)',
    type: 'enum',
    flag: '--reasoning-format',
    default: 'auto',
    choices: [
      { value: 'auto' },
      { value: 'none' },
      { value: 'deepseek' },
      { value: 'deepseek-legacy' },
    ],
    group: 'advanced',
    advanced: true,
  },
  {
    key: 'offline',
    label: 'Tryb offline (blokowanie sieci)',
    type: 'bool',
    flag: '--offline',
    default: true,
    group: 'server',
  },
  // --- chat/template
  {
    key: 'jinja',
    label: 'Szablon Jinja (chat template)',
    type: 'bool',
    flag: '--jinja',
    offFlag: '--no-jinja',
    default: true,
    group: 'chat',
    description: 'Używa Jinja template engine dla czatu. Wiele modeli tego wymaga.',
  },
];
